uart_communication_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    serial_baudrate: 115200
    sender_timer_value: 100 # milliseconds
    receiver_timer_value: 100 # milliseconds
    steering_angle_topic: "/steering_angle"
    throttle_topic: "/throttle"
    speed_publisher_topic: "/speed"
